# Generated by Django 4.1.4 on 2022-12-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0005_optionmodel_question_alter_resultmodel_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionmodel',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='options', to='testa.questionmodel'),
        ),
    ]
