# Generated by Django 4.1.4 on 2022-12-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0006_alter_optionmodel_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questions', to='testa.testmodel'),
        ),
    ]
