# Generated by Django 4.1.4 on 2022-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0007_alter_questionmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionmodel',
            name='point',
        ),
        migrations.RemoveField(
            model_name='optionmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'simple'), (2, 'text'), (3, 'many choose')], db_index=True, default=1),
        ),
    ]
